# Examples

Below we illustrate some basic usage of `probnum`. We begin by creating random variables, the main objects used as in- and outputs of probabilistic numerical methods.

## Random Variables and Linear Operators

In [1]:
"""
Instantiate and manipulate random variables and linear operators.
"""
import numpy as np
from probnum.probability import RandomVariable, Normal

# Seed
np.random.seed(42)

# Gaussian random variable
X = RandomVariable(distribution=Normal(mean=0.5, cov=1))

# Arithmetic operations between scalars and random variables
Y = 2 * X - 1
print(Y)

# Samples / realizations
Y.sample(size=(2, 3))

<() RandomVariable with dtype=<class 'float'>>


array([[ 0.99342831, -0.2765286 ,  1.29537708],
       [ 3.04605971, -0.46830675, -0.46827391]])

In [2]:
# Arithmetic operations between matrices and random variables
A = np.array([[1, 2], 
              [3, 2]])
X = RandomVariable(distribution=Normal(mean=np.array([1, 2]), cov=np.array([[2, 0], 
                                                                            [0, 5]])))
Y = A @ X

print(Y)
Y.sample(size=3)

<(2,) RandomVariable with dtype=<class 'float'>>


array([[-3.12837959, -1.8451091 ],
       [ 6.37960911, 10.39528139],
       [ 7.70884096,  9.35659646]])

In [7]:
from probnum.linalg import aslinop

# Linear operators applied to random variables
A = aslinop(np.array([[1, 2], 
                      [3, 4]]))
Y = A @ X

print(Y)
Y.sample(size=(3,2))

<(2,) RandomVariable with dtype=<class 'float'>>


array([[[ 7.01707441, 14.19400815],
        [ 5.5404421 , 12.69569096]],

       [[-3.88312865, -7.62349784],
        [ 3.83845463,  8.43283096]],

       [[13.95757001, 29.98245179],
        [ 3.43087185, 11.01075812]]])

In [ ]:
# Matrix-variate normal distribution

In [4]:
# Linear operators _as_ random variables

## Linear Systems

In [5]:
"""
Create and solve linear systems using a probabilistic linear solver.
"""
from probnum.linalg import problinsolve

# Linear system
A = np.random.rand(10, 10)
A = A.dot(A.T) + 10 * np.eye(10) # Symmetrize and make diagonally dominant
b = np.random.rand(10, 1)

# Prior distribution on A
covA = None
A = RandomVariable(shape=A.shape, 
                   dtype=A.dtype, 
                   distribution=Normal(mean=A, cov=covA))

# Probabilistic linear solver
x, A, Ainv, info = problinsolve(A=A, b=b)

# Plot resulting distribution on x, A and Ainv

ValueError: Cannot instantiate normal distribution with mean of type ndarray and covariance of type NoneType.

## Discretized Differential Equations

In [ ]:
"""
Specify a discretized differential equation as a linear operator and solve it.
"""

In [ ]:
"""
Solve multiple systems with previous posterior as a prior.
"""